---
url: "http://nflix-web:8080"
database:
  host: "pgdb"
  dbname: "nflix"
  user: "postgres"
  password: "qaninja"
api:
  movies: "http://nflix-api-movies:3002"
users:
  cat_manager:
    name: "Tony Stark"
    email: "tony@stark.com"
    pass: "pwd123"
