---
url: "http://nflix-web:8080"
database:
  host: "127.0.0.1"
  dbname: "nflix"
  user: "postgres"
  password: "qaninja"
api:
  movies: "http://nflix-api-movies:3002"
users:
  cat_manager:
    email: "tony@stark.com"
    pass: "pwd123"